import { useEffect, useState } from "react"
import { fetchDashboardStats } from "../../api/admin"
import {
  FailureHeatmapCard,
  InspectionLogsTable,
  STAT_ICONS,
  StatCard,
} from "./DashboardWidgets"
import { AlertBanner } from "../ui/StatusBadge"
import { Skeleton } from "@/components/ui/skeleton"

function DashboardSkeleton() {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-32 rounded-xl" />
        ))}
      </div>
      <Skeleton className="h-80 rounded-xl" />
    </div>
  )
}

export function DashboardPanel({ token }) {
  const [stats, setStats] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")

  useEffect(() => {
    fetchDashboardStats(token)
      .then((data) => {
        setStats(data)
        setLoading(false)
      })
      .catch((err) => {
        setError(err.message)
        setLoading(false)
      })
  }, [token])

  if (loading) return <DashboardSkeleton />

  if (error) {
    return <AlertBanner tone="error">{error}</AlertBanner>
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard
          title="Total all-time"
          value={stats.total_inspections}
          subtitle={`+ ${stats.today_total} logged today`}
          accent="border-t-brand-500"
          icon={STAT_ICONS.total}
        />
        <StatCard
          title="Yield rate"
          value={`${stats.yield_rate}%`}
          subtitle={`${stats.failed_inspections} total defects`}
          accent="border-t-pass"
          icon={STAT_ICONS.yield}
        />
        <StatCard
          title="Top defect reason"
          value={stats.top_defect}
          valueClassName="truncate text-xl font-black text-foreground"
          subtitle="Generated by Gemini AI"
          accent="border-t-fail"
          icon={STAT_ICONS.defect}
        />
        <FailureHeatmapCard stageFailures={stats.stage_failures} />
      </div>

      <InspectionLogsTable logs={stats?.logs} />
    </div>
  )
}
